%%
%% Autogenerated by Thrift Compiler (0.10.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(generate_thrift).
-behaviour(thrift_service).


-include("generate_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% do_generate(This)
function_info('do_generate', params_type) ->
  {struct, []}
;
function_info('do_generate', reply_type) ->
  {struct, {'id_generate_types', 'WorkId'}};
function_info('do_generate', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['do_generate'].

