%%
%% Autogenerated by Thrift Compiler (0.10.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(id_generate_types).

-include("id_generate_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('WorkId') ->
  {struct, [{1, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('WorkId') ->
  {struct, [{1, undefined, string, 'work', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['WorkId'].

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  [].

exception_names() ->
  [].

